apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/SaifRehman/acm-ocpvirt
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: acm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
